config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'works/index'
  root to: "works#index"
  resources :works, only: [:new, :create, :show] do
   resources :buys, only: [:index, :create]
 end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ApplicationRecord
 belongs_to :user
 belongs_to :work
 has_one    :shipping_address
end

app/models/buy_add.rb
class BuyAdd < ApplicationRecord
end

app/models/category.rb
class Category < ActiveHash::Base
 self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '木工' },
   { id: 3, name: '陶器' },
   { id: 4, name: 'グラフィック' },
   { id: 5, name: '楽器' },
   { id: 6, name: '貴金属' },
   { id: 7, name: '小物' },
   { id: 8, name: 'おもちゃ' },
   { id: 9, name: 'その他' },
 ]

 include ActiveHash::Associations
 has_many :works
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
 with_options presence: true do
   validates :postal_code
   validates :shipping_area_id
   validates :town
   validates :address
   validates :phone
 end

 belongs_to :buy
end

app/models/shipping_area.rb
class ShippingArea < ActiveHash::Base
 self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '北海道' },
   { id: 3, name: '青森県' },
   { id: 4, name: '岩手県' },
   { id: 5, name: '宮城県' },
   { id: 6, name: '秋田県' },
   { id: 7, name: '山形県' },
   { id: 8, name: '福島県' },
   { id: 9, name: '茨城県' },
   { id: 10, name: '栃木県' },
   { id: 11, name: '群馬県' },
   { id: 12, name: '埼玉県' },
   { id: 13, name: '千葉県' },
   { id: 14, name: '東京都' },
   { id: 15, name: '神奈川県' },
   { id: 16, name: '新潟県' },
   { id: 17, name: '富山県' },
   { id: 18, name: '石川県' },
   { id: 19, name: '福井県' },
   { id: 20, name: '山梨県' },
   { id: 21, name: '長野県' },
   { id: 22, name: '岐阜県' },
   { id: 23, name: '静岡県' },
   { id: 24, name: '愛知県' },
   { id: 25, name: '三重県' },
   { id: 26, name: '滋賀県' },
   { id: 27, name: '京都府' },
   { id: 28, name: '大阪府' },
   { id: 29, name: '兵庫県' },
   { id: 30, name: '奈良県' },
   { id: 31, name: '和歌山県' },
   { id: 32, name: '鳥取県' },
   { id: 33, name: '島根県' },
   { id: 34, name: '岡山県' },
   { id: 35, name: '広島県' },
   { id: 36, name: '山口県' },
   { id: 37, name: '徳島県' },
   { id: 38, name: '香川県' },
   { id: 39, name: '愛媛県' },
   { id: 40, name: '高知県' },
   { id: 41, name: '福岡県' },
   { id: 42, name: '佐賀県' },
   { id: 43, name: '長崎県' },
   { id: 44, name: '熊本県' },
   { id: 45, name: '大分県' },
   { id: 46, name: '宮崎県' },
   { id: 47, name: '鹿児島県' },
   { id: 48, name: '沖縄県' }
 ]

 include ActiveHash::Associations
 has_many :works
end

app/models/shipping_cost.rb
class ShippingCost < ActiveHash::Base
 self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '着払い（購入者負担）' },
   { id: 3, name: '送料込み（出品者負担）' }
 ]

 include ActiveHash::Associations
 has_many :works
end

app/models/shipping_day.rb
class ShippingDay < ActiveHash::Base
 self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '1~2日で発送' },
   { id: 3, name: '2~3日で発送' },
   { id: 4, name: '4~7日で発送' }
 ]

 include ActiveHash::Associations
 has_many :works
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
    validates :nickname
    validates :first_name
    validates :last_name
    validates :first_name_furigana
    validates :last_name_furigana
    validates :birth_date
  end
  has_many :works
end

app/models/work.rb
class Work < ApplicationRecord

 with_options presence: true do
  validates :work_name
  validates :value, format: { with: /\A[0-9]+\z/ },
                    numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9999999 }
  validates :description
  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :shipping_cost_id
    validates :shipping_area_id
    validates :shipping_day_id
  end
end

belongs_to       :user
has_one          :buy
has_one_attached :video 

extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :shipping_area
  belongs_to :shipping_cost
  belongs_to :shipping_day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :basic_auth

 before_action :configure_permitted_parameters, if: :devise_controller?

 private

 def basic_auth
   authenticate_or_request_with_http_basic do |username, password|
    username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
   end
 end

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :first_name_furigana, :last_name_furigana,:birth_date])
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
  @user = User.find(params[:id])
  @works = current_user.works
 end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @work = Work.all.order('id DESC')
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @work = Work.find(params[:id])
  end

  private
  def work_params
    params.require(:work).permit(:work_name, :category_id, :video, :shipping_area_id, :shipping_day_id,
                                 :shipping_cost_id, :value, :description).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qeity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='ad-footer-contents'>
 <div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>Qeityについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to '利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>開催中オークション</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ジャンル一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>News</h2>
      <ul>
        <li><%= link_to 'ガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <div class='company-name'>© Qeity</div>
 </div>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
 <div>
  <%= link_to image_tag("qeity-logo.png", class:"qeity-icon"), "/" %>
 </div>
  <div class='nav'>
    <ul class='lists'>
      <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, user_path(current_user.id), method: :GET, class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <li><%= link_to '出品する', new_work_path, method: :GET, class: "logout" %></li>

      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
  <div class='top-page'>
    <b class='title'>クリエイターオークション Qeity</b>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='何を見つけたいですか？'>
      <button class="search-button">
       <%= image_tag "search3.jpg", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav-second'>
    <ul class='lists-second'>
      <li><%= link_to 'ジャンル', "#", class:"genre-list" %></li>
      <li><%= link_to 'カテゴリー', "#", class:"category-list" %></li>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("qeity-logo.png", class:"second-logo"), "/" %>
</header>

app/views/users/show.html.erb
<%= render "shared/second-header"%>
<main class="#">
  <div class="#">
    <%= link_to current_user.nickname, user_path(current_user.id), method: :GET, class: "#" %>さんの作品一覧

    <% @works.each do |work| %>
     <% if work.video.attached? %>
      <li class='#'>
       <%= link_to work_path(work.id), method: :get do %>
        <div class='#'>
          <%= video_tag rails_blob_path(work.video), autoplay: :true, loop: :true, muted: :true, class:"move-list"%>
        </div>
        <div class='#'>
          <h3 class='item-name'>
            <%= work.work_name %>
          </h3>
          <div class='#'>
            現在価格<%= work.value %>円<br><%= work.shipping_cost.name %>
            <div class='star-btn'>
            <%= image_tag "good.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    <% end %>

     <% if user_signed_in?  && current_user.id %>
          <%= link_to "編集する", "#", class: "#" %>
          <%= link_to "削除する", "#", class: "#" %>
        </div>
      <% end %>
   <ul class='#'>
    <li><%= link_to '入札中', class: "#" %></li>
    <li><%= link_to '落札品', class: "#" %></li>
   </ul>
</div>
 <%= render "shared/footer" %>

app/views/works/index.html.erb
<%= render "shared/header" %>
<div class='main'>
    <h2 class='index-title'>Qeity(ｸｴｲﾃｨｰ)とは</h2>
  <ul class='reason-lists'>
   <li class='list'>
     <p class='reason-list-description'>製作過程を動画視聴しながら即入札可能！</p>
     <%= image_tag "syokuninn1.png", class:"list-pict" %>
    </li>
    <li class='list'>
     <p class='reason-list-description'>作品に製作段階から関われる！</p>
     <%= image_tag "syokuninn2.png", class:"list-pict" %>
   </li>
   <li class='list'>
    <p class='reason-list-description'>落札後は出来立ての創作品を直配送！</p>
    <%= image_tag "syokuninn3.png", class:"list-pict" %>
   </li>
  </ul>
</div>

  <div class='item-contents'>
      <h2 class='title2'>開催中オークション一覧</h2>
   <ul class='item-lists'>

   <% if @work[0] != nil %>
    <% @work.each do |work| %>
     <% if work.video.attached? %>
      <li class='list'>
       <%= link_to work_path(work.id), method: :get do %>
        <div class='item-img-content'>
          <%= video_tag rails_blob_path(work.video), autoplay: :true, loop: :true, muted: :true, class:"move-list"%>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= work.work_name %>
          </h3>
          <div class='item-price'>
            現在価格<%= work.value %>円<br><%= work.shipping_cost.name %>
            <div class='star-btn'>
            <%= image_tag "good.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

   <% if @work.length == 0 %>
    <li class='list'>
    <%= link_to '#' do %>
    <%= video_tag "/videos/move.mp4", autoplay: :true, loop: :true, muted: :true, autoplay: :true , class:"move-list" %>
    <div class='item-info'>
      <h3 class='item-name'>
        出品サンプル
      </h3>
      <div class='item-price'>
        <span class='item-value'>￥現在価格</span>
        <span>終了時刻 5/14/18:00</span>
        <div class='star-btn'>
          <%= image_tag "good.png", class:"star-icon" %>
          <span class='star-count'>0</span>
          </div>
        </div>
       </div>
      <% end %>
     </li>
    </ul>
   <% end %>
  </div>
<%= render "shared/footer" %>

app/views/works/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag("qeity-logo.png", class:"qeity-icon"), "/" %>
  </header>
  <div class="items-sell-main">
      <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @work, local: true do |f| %>

       <%= render 'shared/error_messages', model: f.object %>
       <div class="img-upload">
       <div class="weight-bold-text">
        出品動画
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <p>
          ※本人の製作過程をmp4やmpg等の動画形式ファイルでご選択ください
        </p>
      <%= f.file_field :video, id:"work-video" %> 
      </div>
    </div>
        
    <div class="new-items">
      <div class="weight-bold-text">
        作品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :work_name, class:"items-text", id:"#", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          製作品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"#", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">製作品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_cost_id, ShippingCost.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_area_id, ShippingArea.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_day_id, ShippingDay.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>

     <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>開始価格<br>(¥1〜9,999,999)<br>手数料は落札価格の5%です</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :value, class:"price-input", id:"item-price", placeholder:"例）500" %>
        </div>
        <div class="price-content"></div>
       </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%= link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
<% end %>

<footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <p class="inc">
      ©︎Qeity,Inc.
    </p>
  </footer>
</div>

app/views/works/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @work.work_name %>
    </h2>


    <div class="item-img-content">
     <% if @work.video.attached? %>
       <%= video_tag rails_blob_path(@work.video), autoplay: :true, loop: :true, muted: :true, class:"move-list"%>
     <% end %>

    <% if @work.buy.present? %> 
        <div class="sold-out">
          <span>Sold Out!!</span>
        </div>
     <% end %>
</div>
   <div class="item-price-box">
     <span class="item-price">
       ￥<%= @work.value %>
     </span>
     <span class="item-postage">
       <%= @work.shipping_cost.name %>
     </span>
   </div>

    <% if user_signed_in? && @work.buy.blank? %>
    <% if current_user.id == @work.user_id %>
     <%= link_to "商品の編集", "#", class: "item-red-btn" %>
     <p class="or-text">or</p>
     <%= link_to "削除", "#", class:"item-destroy" %>
    <% else %>
    <%= link_to "購入画面に進む", "#", class:"item-red-btn"%>
    <% end %>
   <% end %>

    <div class="item-explain-box">
      <span><%= @work.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @work.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @work.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @work.shipping_cost.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @work.shipping_area.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @work.shipping_day.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%# image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <%= image_tag "good.png", class:"favorite-star-icon" ,width:"20",height:"20" %>

        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%# image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%# image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <%# 詳細ページで表示されている商品のカテゴリー名表示 %>
  <a href="#" class="another-item"><%= @work.category.name %>をもっと見る</a>
  <%# //詳細ページで表示されている商品のカテゴリー名を表示 %>
</div>

<%= render "shared/footer" %>